-- MySQL Script generated by MySQL Workbench
-- Mon May  8 12:05:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SpotifyClone`;
CREATE SCHEMA IF NOT EXISTS `SpotifyClone` DEFAULT CHARACTER SET utf8 ;
USE `SpotifyClone` ;

-- -----------------------------------------------------
-- Table `mydb`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`artista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO artista (nome) VALUES ('Beyoncé'), ('Queen'), ('Elis Regina'), ('Baco Exu do Blues'), ('Blind Guardian'), ('Nina Simone');

-- -----------------------------------------------------
-- Table `mydb`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`Album` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `ano_de_lancamento` VARCHAR(45) NOT NULL,
  `artista_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Album_artista1_idx` (`artista_id` ASC) VISIBLE,
  CONSTRAINT `fk_Album_artista1`
    FOREIGN KEY (`artista_id`)
    REFERENCES `SpotifyClone`.`artista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO Album (nome, ano_de_lancamento, artista_id) VALUES ('Renaissance', 2022, 1), ('Jazz', 1978, 2), ('Hot Space', 1982, 2), ('Falso Brilhante', 1998, 3), ('Vento de Maio', 2001, 3), ('QVVJFA?', 2003, 4), ('Somewhere Far Beyond', 2007, 5), ('I Put A Spell On You', 2012, 6);
-- -----------------------------------------------------
-- Table `mydb`.`planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`planos` (
  `id_planos` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(3, 2),
  PRIMARY KEY (`id_planos`))
ENGINE = InnoDB;

INSERT INTO planos (tipo, valor) VALUES ('gratuito', 0), ('familiar', 7.99), ('universitário', 5.99), ('pessoal', 6.99);
-- -----------------------------------------------------
-- Table `mydb`.`pessoa_usuaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`pessoa_usuaria` (
  `id` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NOT NULL,
  `data_da_assinatura` VARCHAR(45) NOT NULL,
  `planos_id_planos` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoa_usuaria_planos1_idx` (`planos_id_planos` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_usuaria_planos1`
    FOREIGN KEY (`planos_id_planos`)
    REFERENCES `SpotifyClone`.`planos` (`id_planos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO pessoa_usuaria (nome, idade, data_da_assinatura, planos_id_planos) VALUES ('Barbara Liskov', 82, '2019-10-20', 1), ('Robert Cecil Martin', 58, '2017-01-06', 1), ('Ada Lovelace', 37, '2017-12-30', 2), ('Martin Fowler', 46, '2017-01-17', 2), ('Sandi Metz', 58, '2018-04-29', 2), ('Paulo Freire', 19, '2018-02-14', 3), ('Bell Hooks', 26, '2018-01-05', 3), ('Christopher Alexander', 85, '2019-06-05', 4), ('Judith Butler', 45, '2020-05-13', 4), ('Jorge Amado', 58, '2017-02-17', 4);
-- -----------------------------------------------------
-- Table `mydb`.`cancoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`cancoes` (
  `idcancoes` INT NOT NULL auto_increment,
  `nome` VARCHAR(45) NOT NULL,
  `duracao` INT NOT NULL,
  `Album_id` INT NOT NULL,
  PRIMARY KEY (`idcancoes`),
  INDEX `fk_cancoes_Album1_idx` (`Album_id` ASC) VISIBLE,
  CONSTRAINT `fk_cancoes_Album1`
    FOREIGN KEY (`Album_id`)
    REFERENCES `SpotifyClone`.`Album` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO cancoes (nome, duracao, Album_id) VALUES ('BREAK MY SOUL', 279, 1), ("VIRGO'S GROOVE", 369, 2), ('ALIEN SUPERSTAR', 116, 3), ("Don't Stop Me Now", 203, 4), ('Under Pressure', 152, 5), ('Como Nossos Pais', 105, 6), ('O Medo de Amar é o Medo de Ser Livre', 207, 7), ("Samba em Paris", 267, 8), ("The Bard's Song", 244, 9), ('Feeling Good', 100, 10);
-- -----------------------------------------------------
-- Table `mydb`.`following`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`following_artist` (
  `artista_id` INT NOT NULL,
  `pessoa_usuaria_id` INT NOT NULL,
  PRIMARY KEY (`artista_id`, `pessoa_usuaria_id`),
  INDEX `fk_artista_has_pessoa_usuaria_pessoa_usuaria1_idx` (`pessoa_usuaria_id` ASC) VISIBLE,
  INDEX `fk_artista_has_pessoa_usuaria_artista1_idx` (`artista_id` ASC) VISIBLE,
  CONSTRAINT `fk_artista_has_pessoa_usuaria_artista1`
    FOREIGN KEY (`artista_id`)
    REFERENCES `SpotifyClone`.`artista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_artista_has_pessoa_usuaria_pessoa_usuaria1`
    FOREIGN KEY (`pessoa_usuaria_id`)
    REFERENCES `SpotifyClone`.`pessoa_usuaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO following_artist (artista_id, pessoa_usuaria_id) VALUES (1, 1), (2, 1), (3, 1), (1, 2), (3, 2), (2, 3), (4, 4), (5, 5), (6, 5), (6, 6), (1, 6), (6, 7), (3, 9), (2, 10);
-- -----------------------------------------------------
-- Table `mydb`.`historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SpotifyClone`.`historico` (
  `pessoa_usuaria_id` INT NOT NULL,
  `cancoes_idcancoes` INT NOT NULL,
  `data_reproducao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`pessoa_usuaria_id`, `cancoes_idcancoes`),
  INDEX `fk_pessoa_usuaria_has_cancoes_cancoes1_idx` (`cancoes_idcancoes` ASC) VISIBLE,
  INDEX `fk_pessoa_usuaria_has_cancoes_pessoa_usuaria1_idx` (`pessoa_usuaria_id` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_usuaria_has_cancoes_pessoa_usuaria1`
    FOREIGN KEY (`pessoa_usuaria_id`)
    REFERENCES `SpotifyClone`.`pessoa_usuaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_usuaria_has_cancoes_cancoes1`
    FOREIGN KEY (`cancoes_idcancoes`)
    REFERENCES `SpotifyClone`.`cancoes` (`idcancoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO historico (pessoa_usuaria_id, cancoes_idcancoes, data_reproducao) VALUES (1, 8, '2022-02-28 10:45:55'), (1, 2, '2020-05-02 05:30:35'), (1, 10, '2020-03-06 11:22:33'), (2, 10, '2022-08-05 08:05:17'), (2, 7, '2020-01-02 07:40:33'), (3, 10, '2020-11-13 16:55:13'), (3, 2, '2020-12-05 18:38:30'), (4, 8, '2021-08-15 17:10:10'), (5, 8, '2022-01-09 01:44:33'), (5, 5, '2020-08-06 15:23:43'), (6, 7, '2017-01-24 00:31:17'), (6, 1, '2017-10-12 12:35:20'), (7, 4, '2011-12-15 22:30:49'), (8, 4, '2012-03-17 14:56:41'), (9, 9, '2022-02-24 21:14:22'), (10, 3, '2015-12-13 08:30:22');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


